version: "3.5"

services:
  app:
    build: .
    container_name: f1-api
    ports:
      - 3090:3090
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=changeme
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always


volumes:
    postgres: